### ISSUE TITLE
다음 버전 release 일정 문의

### ISSUE THREAD

**Issue by grasseat** [naver/arcus-spring#70]
안녕하세요. 
사내에서 스프링 latest 버전으로의 bump up을 준비하고 있는 프로젝트가 있습니다.
https://github.com/naver/arcus-spring/pull/63 PR이 반영된 다음 release 일정이 언제인지 알 수 있을까요?
가능하시다면 minor fix 버전으로라도 패치 해 주신다면 감사하겠습니다!

**Comment by jhpark816** [comment]
@grasseat 차주 초에 논의해 보고, 가능하면 빠르게 릴리즈하겠습니다.

**Comment by jhpark816** [comment]
@grasseat 

arcus-spring 1.13.5 버전을 릴리즈하였습니다.
- https://github.com/naver/arcus-spring/releases/tag/1.13.5

JaM2in maver repo에도 배포가 된 상태입니다.
- https://mvnrepository.com/artifact/com.jam2in.arcus/arcus-spring

**Comment by grasseat** [comment]
감사합니다! 릴리즈 확인하여 이슈 close 하겠습니다.
